### PR TITLE
Fix compiling on Windows, and fix tests against ExactPredicates by refining float range

### LINKED ISSUE #4: Tests failing, or my machine is bad
Maybe my fix to compiling predicates.c has failed somewhere, but it seems the tests are failing here:

```julia
julia> @check function orient_against_exact(a=complexgen, b=complexgen, c=complexgen)
           dir = orient(a,b,c)
           event!("Adaptive", dir)
           edir = ExactPredicates.orient(a,b,c)
           event!("Exact", edir)
           dir == edir
       end
Found counterexample
  Context: orient_against_exact

  Arguments:
      a::ComplexF64 = 0.0 + 0.0im
      b::ComplexF64 = 0.0 + 5.0e-324im
      c::ComplexF64 = 5.0e-324 + 0.0im

  Events:
    Adaptive
        0
    Exact
        -1

julia> @check function orient_c_against_exact(a=complexgen, b=complexgen, c=complexgen)
           dir = CPredicates.orient(a,b,c)
           event!("Original", dir)
           edir = ExactPredicates.orient(a,b,c)
           event!("Exact", edir)
           dir == edir
       end
Found counterexample
  Context: orient_c_against_exact

  Arguments:
      a::ComplexF64 = 0.0 + 0.0im
      b::ComplexF64 = 0.0 + 5.0e-324im
      c::ComplexF64 = 5.0e-324 + 0.0im

  Events:
    Original
        0
    Exact
        -1
```

If you have the time, Is this something you're able to please see if you can reproduce? I'm on a Windows machine and so can't check the results without #3 which changes the .c file

(Also, the `Exact` result is probably the correct one since `orient(a, b, c) = -2.5e-647`)

### PR DESCRIPTION
**Pull request by DanielVandH**
Fixes #4. Since the algorithms are said to be guaranteed correct only for exponents in $[-142, 201]$, the tests against ExactPredicates now only test in this range. 

I accidentally included my Windows fixes in this branch so I closed #3 and am using this for both. Hopefully that's fine.

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -26,71 +36,68 @@ function orient(a, b, c)
...
+    cdir = CPredicates.orient(a, b, c)
     event!("Original", cdir)
     dir == cdir
 end
 
 # The next two should agree
-@check function orient_against_exact(a=complexgen, b=complexgen, c=complexgen)
-    dir = orient(a,b,c)
+@check function orient_against_exact(a=complexgen2, b=complexgen2, c=complexgen2)
+    assume!(all(x -> iszero(x) || exponent(abs(x)) ∈ -141:201, (a.re, a.im, b.re, b.im, c.re, c.im)))
```
Comment (vchuravy) [inline test/runtests.jl]: Can you add a comment, with a reference to the paper? Maybe also a short statement in the Readme?

**Review by vchuravy — APPROVED** [review]

File: test/runtests.jl (hunk 1 above)
Comment (DanielVandH) [reply test/runtests.jl]: Done

**Comment by DanielVandH** [comment]
Was using `141` when it should be `142`, should be good now
